routes/admin.php
<?php
use Illuminate\Support\Facades\Route;


//we 'll not use admin prefix in this file because already fix in ROute service provider

Route::namespace('Admin')->prefix('admin')->as('admin.')->group(function (){
    Route::namespace('Auth')->group(function (){
//        Route::get('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('showLoginForm');
//        Route::post('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('login');
        Route::get('/login', [\App\Http\Controllers\Admin\AuthController::class, 'loginForm'])->name('showLoginForm');
        Route::post('/login', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login');
        Route::post('/logout', [\App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');
    });

    Route::get('/', [\App\Http\Controllers\Admin\AdminController::class, 'index'])->name('home');
    Route::get('/edit/{admin}', [\App\Http\Controllers\Admin\AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/update-profile', [\App\Http\Controllers\Admin\AdminController::class, 'updateProfile'])->name('updateProfile');


    //    Product Route's
    Route::namespace('Order')->prefix('orders')->as('order.')->group(function (){

        Route::get('/pending',[\App\Http\Controllers\Admin\Order\OrderController::class,'pending'])->name('pending');
        Route::get('/acceptedNew',[\App\Http\Controllers\Admin\Order\OrderController::class,'acceptedNew'])->name('acceptedNew');
        Route::get('/complete',[\App\Http\Controllers\Admin\Order\OrderController::class,'complete'])->name('complete');
        Route::get('/rejected',[\App\Http\Controllers\Admin\Order\OrderController::class,'rejected'])->name('rejected');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Order\OrderController::class,'changeStatus'])->name('changeStatus');
        Route::post('/order-accepted-status',[\App\Http\Controllers\Admin\Order\OrderController::class,'acceptedStatus'])->name('acceptedStatus');

    });

    // restaurants routes
    Route::namespace('Restaurant')->prefix('restaurants')->as('restaurant.')->group(function (){
        Route::get('/', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'approved'])->name('approved');
        Route::get('/pending', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'pending'])->name('pending');
        Route::get('/rejected', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'rejected'])->name('rejected');
        Route::get('/form', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'form'])->name('form');
        Route::post('/store', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'store'])->name('store');
        Route::post('/update', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'update'])->name('update');
        Route::post('/delete', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'destroy'])->name('delete');
        Route::post('/change-status', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'changeStatus'])->name('changeStatus');

    });

    // Users routes
    Route::namespace('User')->prefix('users')->as('user.')->group(function (){
        Route::get('/form', [\App\Http\Controllers\Admin\User\UsersController::class, 'form'])->name('form');
        Route::get('/active', [\App\Http\Controllers\Admin\User\UsersController::class, 'active'])->name('active');
        Route::get('/inactive', [\App\Http\Controllers\Admin\User\UsersController::class, 'inActive'])->name('inActive');
        Route::post('/store', [\App\Http\Controllers\Admin\User\UsersController::class, 'store'])->name('store');
//        Route::post('/edit/{id}', [\App\Http\Controllers\Admin\User\UsersController::class, 'edit'])->name('edit');
        Route::post('/update', [\App\Http\Controllers\Admin\User\UsersController::class, 'update'])->name('update');
        Route::post('/delete', [\App\Http\Controllers\Admin\User\UsersController::class, 'destroy'])->name('delete');
        Route::post('/change-status', [\App\Http\Controllers\Admin\User\UsersController::class, 'changeStatus'])->name('changeStatus');
    });

    //    Category Route's
    Route::namespace('Categories')->prefix('category')->as('category.')->group(function (){
        Route::get('/',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'create'])->name('create');
        Route::post('/store',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'update'])->name('update');
        Route::post('/delete',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'destroy'])->name('delete');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'changeStatus'])->name('changeStatus');
    });


//    Product Route's
    Route::namespace('Products')->prefix('product')->as('product.')->group(function (){

        Route::get('/approved',[\App\Http\Controllers\Admin\Products\ProductController::class,'approved'])->name('approved');
        Route::get('/pending',[\App\Http\Controllers\Admin\Products\ProductController::class,'pending'])->name('pending');
        Route::get('/rejected',[\App\Http\Controllers\Admin\Products\ProductController::class,'rejected'])->name('rejected');
        Route::post('/update',[\App\Http\Controllers\Admin\Products\ProductController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Products\ProductController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Admin\Products\ProductController::class,'delete'])->name('delete');

    });

    //    Product Route's
    Route::namespace('Deals')->prefix('deal')->as('deal.')->group(function (){

        Route::get('/approved',[App\Http\Controllers\Admin\Deals\DealController::class,'approved'])->name('approved');
        Route::get('/pending',[App\Http\Controllers\Admin\Deals\DealController::class,'pending'])->name('pending');
        Route::get('/rejected',[App\Http\Controllers\Admin\Deals\DealController::class,'rejected'])->name('rejected');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Deals\DealController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Admin\Deals\DealController::class,'destroy'])->name('delete');

    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
//use App\Http\Controllers\Restaurant\RestaurantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::namespace('Restaurant')->prefix('restaurant')->as('restaurants.')->group(function (){
    Route::namespace('Auth')->group(function (){
//        Route::get('/login', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'showLoginForm'])->name('showLoginForm');
//        Route::post('/login', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'login'])->name('login');
//        Route::post('/logout', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'logout'])->name('logout');
        Route::get('/register', [\App\Http\Controllers\Restaurant\Auth\RegisterController::class, 'showRegistrationForm'])->name('showRegistrationForm');
        Route::post('/register', [\App\Http\Controllers\Restaurant\Auth\RegisterController::class, 'register'])->name('register');

        Route::get('/login', [\App\Http\Controllers\Restaurant\AuthController::class, 'loginForm'])->name('showLoginForm');
        Route::post('/login', [\App\Http\Controllers\Restaurant\AuthController::class, 'login'])->name('login');
        Route::post('/logout', [\App\Http\Controllers\Restaurant\AuthController::class, 'logout'])->name('logout');
    });

    Route::middleware(['Restaurant'])->group(function(){

    Route::get('/', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'index'])->name('home');
    Route::get('/edit/{restaurant}', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'editProfile'])->name('editProfile');
    Route::post('/update-profile', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'updateProfile'])->name('updateProfile');
    Route::get('/forget-password', [\App\Http\Controllers\Restaurant\ForgetPasswordController::class, 'forgetPassword'])->name('forgetPassword');
    Route::post('/new-password', [\App\Http\Controllers\Restaurant\ForgetPasswordController::class, 'newPassword'])->name('newPassword');





    // Category Route's
    Route::namespace('Categories')->prefix('category')->as('category.')->group(function (){
        Route::get('/',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'index'])->name('list');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'update'])->name('update');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'destroy'])->name('delete');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'changeStatus'])->name('changeStatus');
    });

    //    Deal Route's
    Route::namespace('Deal')->prefix('deal')->as('deal.')->group(function (){

        Route::get('/create',[App\Http\Controllers\Restaurant\Deal\DealController::class,'create'])->name('create');
        Route::get('/enable',[App\Http\Controllers\Restaurant\Deal\DealController::class,'enable'])->name('enable');
        Route::get('/disable',[App\Http\Controllers\Restaurant\Deal\DealController::class,'disable'])->name('disable');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'destroy'])->name('delete');

    });
    //    Product Route's
    Route::namespace('Order')->prefix('order')->as('order.')->group(function (){

        Route::get('/order-pending',[App\Http\Controllers\Restaurant\Order\OrderController::class,'pending'])->name('pending-order');
        Route::get('/order-accepted',[App\Http\Controllers\Restaurant\Order\OrderController::class,'accepted'])->name('accepted-order');
        Route::get('/order-complete',[App\Http\Controllers\Restaurant\Order\OrderController::class,'complete'])->name('complete-order');
        Route::get('/order-rejected',[App\Http\Controllers\Restaurant\Order\OrderController::class,'rejected'])->name('rejected-order');
        Route::post('/order-change-status',[App\Http\Controllers\Restaurant\Order\OrderController::class,'changeStatus'])->name('changeStatus-order');
        Route::post('/order-accepted-status',[App\Http\Controllers\Restaurant\Order\OrderController::class,'acceptedStatus'])->name('acceptedStatus-order');

    });
    //    Product Route's
    Route::namespace('Products')->prefix('product')->as('product.')->group(function (){

        Route::get('/create',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'create'])->name('create');
        Route::get('/approved',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'approved'])->name('approved');
        Route::get('/rejected',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'rejected'])->name('rejected');
        Route::get('/pending',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'pending'])->name('pending');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'destroy'])->name('delete');

    });

    });

});

Route::namespace("Web")->group(function (){
    /* Checkout routes */
    Route::get("checkout",[\App\Http\Controllers\Web\CheckoutController::class,"index"])->name('index');
    Route::get("restaurant/{slug}",[\App\Http\Controllers\Web\RestaurantController::class,"details"])->name('restaurant-detail');
    Route::get("orders",[\App\Http\Controllers\Web\OrderController::class,"index"])->name('orders');
});

//demo
Route::get('/', function () {
    return view('web.home');
});
Route::get('about',function (){
   return view('web.about');
});
Route::get('contact',function (){
    return view('web.contact');
});

Route::get('cart',function (){
    return view('web.cart');
});


Route::get('detail',function (){
    return view('web.detailpage');
});

Route::get('categoryproducts',function (){
    return view('web.categoryproduct');
});

resources/views/admin/index.blade.php
@extends('admin.layouts.app')
@section('title','Admin Dashboard')
@section('content')


<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>

<!-- Content Row -->
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.restaurant.pending')}}">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total Pending Restaurants</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Models\Restaurant::where('status','pending')->count()}}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-utensils fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.restaurant.approved')}}">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Total Approved (Restaurants)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Models\Restaurant::where('status','approved')->count()}}</div>
                    </div>
                    <div class="col-auto">
{{--                        <i class="fas fa-utensils"></i>--}}
                        <i class="fas fa-utensils fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.user.active')}}">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Active User's
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{\App\Models\User::where('is_verified',1)->count()}}</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                         style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                         aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.user.inActive')}}">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            In Active User's</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Models\User::where('is_verified',0)->count()}}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>
</div>
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.product.pending')}}">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total Product (Pending)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Models\Product::where('status','pending')->count()}}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-list-alt fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.deal.pending')}}">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Total Deal's (Pending)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Models\Deal::where('status','pending')->count()}}</div>
                    </div>
                    <div class="col-auto">
                        {{--                        <i class="fas fa-utensils"></i>--}}
                        <i class="fas fa-gift fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.order.pending')}}">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">New Order (Pending)
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{\App\Models\User::where('is_verified',1)->count()}}</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                         style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                         aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-shipping-fast fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <a href="{{route('admin.category.index')}}">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Total Categories</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{\App\Models\Category::count()}}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fa fa-list-alt fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
        </a>
    </div>
</div>


@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.app')
@section('title','Admin Profile')
@section('content')

    <div class="card mb-3">
        <div class="card-header">
            <p><i class="fa fa-check-square-o"></i>Update Admin Profile</p>
        </div>

        <div class="card-body">
            <form class="update-form" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" value="{{$admin->first_name}}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                        <label>Email</label>
                        <input type="email" name="email" class="form-control" value="{{$admin->email}}" disabled="">
                        </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-6">
                        <div class="form-group">
                        <label>New Password</label>
                        <div class="d-flex position-relative justify-content-end">
                            <input type="password" name="password" id="password" class="form-control" value="" placeholder="New Password">
                            <i class="fa fa-eye position-absolute" id="password-eye" style="margin: 11px;"></i>
                        </div>
                    </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                        <label>Confirm Password</label>
                        <div class="d-flex position-relative justify-content-end">
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" value="" placeholder="Confirm Password">
                            <i class="fa fa-eye position-absolute" id="password-eye2" style="margin: 11px;"></i>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-3">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Profile Image</label>
                            <input type="file" style="height: auto" name="image" id="customFileEg1" class="form-control" onchange="loadFile(event)">

                        </div>
                    </div>

                    <div class="col-md-2">
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            <center>
                                <img class="mt-3" style="width: 15%;border: 1px solid; border-radius: 10px;"
                                     id="output" src="{{asset($admin->avatar)}}" alt="image"/>
                            </center>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary create-user" style="background: #ff982f;border: none;float: right" type="submit">Update</button>


            </form>


        </div>
    </div>
@endsection
@section('script')
    <script>

        /* START - preview image */
        var loadFile = function(event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
        $('#password-eye').hover(function () {
            $('#password').attr('type', 'text');
        }, function () {
            $('#password').attr('type', 'password');
        });

        $('#password-eye2').hover(function () {
            $('#password_confirmation').attr('type', 'text');
        }, function () {
            $('#password_confirmation').attr('type', 'password');
        });

        $(".update-form").submit(function(e){
            e.preventDefault();
            // let data = $(this).serialize();
            let data = $('.update-form');
            data = new FormData(data[0]);
            var pass = $('#password').val();
            if(pass){
                if(pass.length < 8){
                    // error
                    return alert('Password should be at least 8 character');
                }
            }
            //blockUi();
            $.ajax({
                type: 'POST',
                url: '{{ route('admin.updateProfile') }}',
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                success:function(data) {
                    //$.unblockUI();
                    if(data.status == 1){
                        successMsg(data.message);
                        window.location.reload();
                    }
                    if(data.status == 0){
                        errorMsg(data.message);
                    }
                },
                error:function(data) {
                    console.log('error');
                    // $.unblockUI();
                }
            });
        });
    </script>



@endsection