routes/admin.php
<?php
use Illuminate\Support\Facades\Route;


//we 'll not use admin prefix in this file because already fix in ROute service provider

Route::namespace('Admin')->prefix('admin')->as('admin.')->group(function (){
    Route::namespace('Auth')->group(function (){
//        Route::get('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('showLoginForm');
//        Route::post('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('login');
        Route::get('/login', [\App\Http\Controllers\Admin\AuthController::class, 'loginForm'])->name('showLoginForm');
        Route::post('/login', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login');
        Route::post('/logout', [\App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');
    });

    Route::get('/', [\App\Http\Controllers\Admin\AdminController::class, 'index'])->name('home');
    Route::get('/edit/{admin}', [\App\Http\Controllers\Admin\AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/update-profile', [\App\Http\Controllers\Admin\AdminController::class, 'updateProfile'])->name('updateProfile');


    //    Product Route's
    Route::namespace('Order')->prefix('orders')->as('order.')->group(function (){

        Route::get('/pending',[\App\Http\Controllers\Admin\Order\OrderController::class,'pending'])->name('pending');
        Route::get('/acceptedNew',[\App\Http\Controllers\Admin\Order\OrderController::class,'acceptedNew'])->name('acceptedNew');
        Route::get('/complete',[\App\Http\Controllers\Admin\Order\OrderController::class,'complete'])->name('complete');
        Route::get('/rejected',[\App\Http\Controllers\Admin\Order\OrderController::class,'rejected'])->name('rejected');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Order\OrderController::class,'changeStatus'])->name('changeStatus');
        Route::post('/order-accepted-status',[\App\Http\Controllers\Admin\Order\OrderController::class,'acceptedStatus'])->name('acceptedStatus');

    });

    // restaurants routes
    Route::namespace('Restaurant')->prefix('restaurants')->as('restaurant.')->group(function (){
        Route::get('/', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'approved'])->name('approved');
        Route::get('/pending', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'pending'])->name('pending');
        Route::get('/rejected', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'rejected'])->name('rejected');
        Route::get('/form', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'form'])->name('form');
        Route::post('/store', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'store'])->name('store');
        Route::post('/update', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'update'])->name('update');
        Route::post('/delete', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'destroy'])->name('delete');
        Route::post('/change-status', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'changeStatus'])->name('changeStatus');

    });

    // Users routes
    Route::namespace('User')->prefix('users')->as('user.')->group(function (){
        Route::get('/form', [\App\Http\Controllers\Admin\User\UsersController::class, 'form'])->name('form');
        Route::get('/active', [\App\Http\Controllers\Admin\User\UsersController::class, 'active'])->name('active');
        Route::get('/inactive', [\App\Http\Controllers\Admin\User\UsersController::class, 'inActive'])->name('inActive');
        Route::post('/store', [\App\Http\Controllers\Admin\User\UsersController::class, 'store'])->name('store');
//        Route::post('/edit/{id}', [\App\Http\Controllers\Admin\User\UsersController::class, 'edit'])->name('edit');
        Route::post('/update', [\App\Http\Controllers\Admin\User\UsersController::class, 'update'])->name('update');
        Route::post('/delete', [\App\Http\Controllers\Admin\User\UsersController::class, 'destroy'])->name('delete');
        Route::post('/change-status', [\App\Http\Controllers\Admin\User\UsersController::class, 'changeStatus'])->name('changeStatus');
    });

    //    Category Route's
    Route::namespace('Categories')->prefix('category')->as('category.')->group(function (){
        Route::get('/',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'create'])->name('create');
        Route::post('/store',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'update'])->name('update');
        Route::post('/delete',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'destroy'])->name('delete');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'changeStatus'])->name('changeStatus');
    });


//    Product Route's
    Route::namespace('Products')->prefix('product')->as('product.')->group(function (){

        Route::get('/approved',[\App\Http\Controllers\Admin\Products\ProductController::class,'approved'])->name('approved');
        Route::get('/pending',[\App\Http\Controllers\Admin\Products\ProductController::class,'pending'])->name('pending');
        Route::get('/rejected',[\App\Http\Controllers\Admin\Products\ProductController::class,'rejected'])->name('rejected');
        Route::post('/update',[\App\Http\Controllers\Admin\Products\ProductController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Products\ProductController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Admin\Products\ProductController::class,'delete'])->name('delete');

    });

    //    Product Route's
    Route::namespace('Deals')->prefix('deal')->as('deal.')->group(function (){

        Route::get('/approved',[App\Http\Controllers\Admin\Deals\DealController::class,'approved'])->name('approved');
        Route::get('/pending',[App\Http\Controllers\Admin\Deals\DealController::class,'pending'])->name('pending');
        Route::get('/rejected',[App\Http\Controllers\Admin\Deals\DealController::class,'rejected'])->name('rejected');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Deals\DealController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Admin\Deals\DealController::class,'destroy'])->name('delete');

    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
//use App\Http\Controllers\Restaurant\RestaurantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::namespace('Restaurant')->prefix('restaurant')->as('restaurants.')->group(function (){
    Route::namespace('Auth')->group(function (){
//        Route::get('/login', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'showLoginForm'])->name('showLoginForm');
//        Route::post('/login', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'login'])->name('login');
//        Route::post('/logout', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'logout'])->name('logout');
        Route::get('/register', [\App\Http\Controllers\Restaurant\Auth\RegisterController::class, 'showRegistrationForm'])->name('showRegistrationForm');
        Route::post('/register', [\App\Http\Controllers\Restaurant\Auth\RegisterController::class, 'register'])->name('register');

        Route::get('/login', [\App\Http\Controllers\Restaurant\AuthController::class, 'loginForm'])->name('showLoginForm');
        Route::post('/login', [\App\Http\Controllers\Restaurant\AuthController::class, 'login'])->name('login');
        Route::post('/logout', [\App\Http\Controllers\Restaurant\AuthController::class, 'logout'])->name('logout');
    });

    Route::middleware(['Restaurant'])->group(function(){

    Route::get('/', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'index'])->name('home');
    Route::get('/edit/{restaurant}', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'editProfile'])->name('editProfile');
    Route::post('/update-profile', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'updateProfile'])->name('updateProfile');
    Route::get('/forget-password', [\App\Http\Controllers\Restaurant\ForgetPasswordController::class, 'forgetPassword'])->name('forgetPassword');
    Route::post('/new-password', [\App\Http\Controllers\Restaurant\ForgetPasswordController::class, 'newPassword'])->name('newPassword');





    // Category Route's
    Route::namespace('Categories')->prefix('category')->as('category.')->group(function (){
        Route::get('/',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'index'])->name('list');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'update'])->name('update');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'destroy'])->name('delete');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'changeStatus'])->name('changeStatus');
    });

    //    Deal Route's
    Route::namespace('Deal')->prefix('deal')->as('deal.')->group(function (){

        Route::get('/create',[App\Http\Controllers\Restaurant\Deal\DealController::class,'create'])->name('create');
        Route::get('/enable',[App\Http\Controllers\Restaurant\Deal\DealController::class,'enable'])->name('enable');
        Route::get('/disable',[App\Http\Controllers\Restaurant\Deal\DealController::class,'disable'])->name('disable');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'destroy'])->name('delete');

    });
    //    Product Route's
    Route::namespace('Order')->prefix('order')->as('order.')->group(function (){

        Route::get('/order-pending',[App\Http\Controllers\Restaurant\Order\OrderController::class,'pending'])->name('pending-order');
        Route::get('/order-accepted',[App\Http\Controllers\Restaurant\Order\OrderController::class,'accepted'])->name('accepted-order');
        Route::get('/order-complete',[App\Http\Controllers\Restaurant\Order\OrderController::class,'complete'])->name('complete-order');
        Route::get('/order-rejected',[App\Http\Controllers\Restaurant\Order\OrderController::class,'rejected'])->name('rejected-order');
        Route::post('/order-change-status',[App\Http\Controllers\Restaurant\Order\OrderController::class,'changeStatus'])->name('changeStatus-order');
        Route::post('/order-accepted-status',[App\Http\Controllers\Restaurant\Order\OrderController::class,'acceptedStatus'])->name('acceptedStatus-order');

    });
    //    Product Route's
    Route::namespace('Products')->prefix('product')->as('product.')->group(function (){

        Route::get('/create',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'create'])->name('create');
        Route::get('/approved',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'approved'])->name('approved');
        Route::get('/rejected',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'rejected'])->name('rejected');
        Route::get('/pending',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'pending'])->name('pending');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'destroy'])->name('delete');

    });

    });

});

Route::namespace("Web")->group(function (){
    /* Checkout routes */
    Route::get("checkout",[\App\Http\Controllers\Web\CheckoutController::class,"index"])->name('index');
    Route::get("restaurant/{slug}",[\App\Http\Controllers\Web\RestaurantController::class,"details"])->name('restaurant-detail');
    Route::get("orders",[\App\Http\Controllers\Web\OrderController::class,"index"])->name('orders');
});

//demo
Route::get('/', function () {
    return view('web.home');
});
Route::get('about',function (){
   return view('web.about');
});
Route::get('contact',function (){
    return view('web.contact');
});

Route::get('cart',function (){
    return view('web.cart');
});


Route::get('detail',function (){
    return view('web.detailpage');
});

Route::get('categoryproducts',function (){
    return view('web.categoryproduct');
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('title','Just Halaall Admin')</title>

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{{ asset("assets/web/images/index.jpg") }}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{{ asset("assets/web/images/index.jpg") }}">
{{--include css blade file--}}
    @include('admin.layouts.css')
    <style>
        .custom-file-label-sm::after{
            height: calc(1.1em + .75rem);
            line-height: 1.25;
        }
        .custom-file-label-sm{
            height: calc(1.1em + .75rem + 2px);
        }
    </style>
    @yield('style')
</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

  @include('admin.layouts.sidebar')

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
           @include('admin.layouts.navbar')
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

           @yield('content')

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
       @include('admin.layouts.footer')
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>


{{--include Js file--}}
@include('admin.layouts.js')

</body>

</html>

resources/views/admin/layouts/css.blade.php
<!-- Custom fonts for this template-->
<link href="{{asset('assets/admin/vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{asset('assets/admin/css/sb-admin-2.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
{{--    For ajax UI Message CSS File--}}
<link href="{{asset('assets/admin/css/jquery-ui.css')}}" rel="stylesheet" type="text/css"/>
<link href="{{asset('assets/admin/css/toastr.css')}}" rel="stylesheet" type="text/css"/>
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
{{--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"/>--}}
{{--<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">--}}

resources/views/admin/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Justhalaall</span>
        </div>
    </div>
</footer>

resources/views/admin/layouts/js.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{asset('assets/admin/vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('assets/admin/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<!-- Core plugin JavaScript-->
<script src="{{asset('assets/admin/vendor/jquery-easing/jquery.easing.min.js')}}"></script>

<!-- Custom scripts for all pages-->
<script src="{{asset('assets/admin/js/sb-admin-2.min.js')}}"></script>

<!-- Page level plugins -->
{{--<script src="{{asset('assets/admin/vendor/chart.js/Chart.min.js')}}"></script>--}}

<!-- Page level custom scripts -->
{{--<script src="{{asset('assets/admin/js/demo/chart-area-demo.js')}}"></script>--}}
{{--<script src="{{asset('assets/admin/js/demo/chart-pie-demo.js')}}"></script>--}}
<script src="{{asset('assets/admin/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/admin/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/admin/js/demo/datatables-demo.js')}}"></script>
{{--JS files for UI Ajax messages--}}
<script src="{{asset('assets/admin/js/jquery.blockUI.js')}}"></script>
<script src="{{asset('assets/admin/js/jquery-ui.js')}}"></script>
<script src="{{asset('assets/admin/js/jquery-ui.min.js')}}"></script>
<script src="{{asset('assets/admin/js/toastr.min.js')}}"></script>

{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script>--}}
<script src="{{asset('assets/admin/js/bootstrap-toggle.min.js')}}"></script>
<script>
    /* START - blockUi */
    function blockUi(){
        $.blockUI({
            css: {
                border: 'none',
                padding: '15px',
                backgroundColor: '#000',
                '-webkit-border-radius': '10px',
                '-moz-border-radius': '10px',
                opacity: .5,
                color: '#fff'
            }
        });
    }
    function successMsg(_msg){
        window.toastr.success(_msg);
    }
    function errorMsg(_msg){
        window.toastr.error(_msg);
    }
    function warningMsg(_msg){
        window.toastr.warning(_msg);
    }
</script>


<script>
    $('#sidebarToggle').click(function(){
        $('.fa-laugh-wink').toggle();
    });

    function blockUi(){
        $.blockUI({
            css: {
                border: 'none',
                padding: '15px',
                backgroundColor: '#000',
                '-webkit-border-radius': '10px',
                '-moz-border-radius': '10px',
                opacity: .5,
                color: '#fff'
            }
        });
    }


    function successMsg(_msg){
        window.toastr.success(_msg);
    }

    function errorMsg(_msg){
        window.toastr.error(_msg);
    }

    function warningMsg(_msg){
        window.toastr.warning(_msg);
    }



</script>

@yield('script')

resources/views/admin/layouts/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/admin">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink" style="display: none;"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Just Halaall <sup>Admin</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('admin.home') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
{{--    <div class="sidebar-heading">Restaurant</div>--}}
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-utensils"></i>
            <span>Restaurants</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Restaurant Components:</h6>
                <a class="collapse-item" href="{{route('admin.restaurant.form')}}">Add New</a>
                <a class="collapse-item" href="{{ route('admin.restaurant.approved') }}">Approved</a>
                <a class="collapse-item" href="{{ route('admin.restaurant.pending') }}">Pending</a>
                <a class="collapse-item" href="{{ route('admin.restaurant.rejected') }}">Rejected</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsecategory" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-list-alt"></i>
            <span>Categories</span>
        </a>
        <div id="collapsecategory" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category Components:</h6>
                <a class="collapse-item" href="{{route('admin.category.create')}}">Add New</a>
                <a class="collapse-item" href="{{route('admin.category.index')}}">List</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsedeals" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-gift"></i>
            <span>Deal's</span>
        </a>
        <div id="collapsedeals" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                                <h6 class="collapse-header">Deals Components:</h6>
                <a class="collapse-item" href="{{route('admin.deal.approved')}}">Approved</a>
                <a class="collapse-item" href="{{route('admin.deal.pending')}}">Pending</a>
                <a class="collapse-item" href="{{route('admin.deal.rejected')}}">Rejected</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseproduct" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-list"></i>
            <span>Products</span>
        </a>
        <div id="collapseproduct" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                                <h6 class="collapse-header">Product Components:</h6>
                <a class="collapse-item" href="{{route('admin.product.approved')}}">Approved</a>
                <a class="collapse-item" href="{{ route('admin.product.pending') }}">Pending</a>
                <a class="collapse-item" href="{{ route('admin.product.rejected') }}">Rejected</a>
            </div>
        </div>
    </li>


    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseorder" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-shipping-fast"></i>
            <span>Order's</span>
        </a>
        <div id="collapseorder" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                                <h6 class="collapse-header">Order Components:</h6>
                <a class="collapse-item" href="/admin/orders/pending">Pending</a>
                <a class="collapse-item" href="/admin/orders/acceptedNew">Accepted</a>
                <a class="collapse-item" href="/admin/orders/complete">Complete</a>
                <a class="collapse-item" href="/admin/orders/rejected">Rejected</a>
            </div>
        </div>
    </li>
    <!-- Divider -->
{{--    <hr class="sidebar-divider d-none d-md-block">--}}

    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
{{--    <div class="sidebar-heading">Restaurant</div>--}}
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUser" aria-expanded="true" aria-controls="collapseUser">
            <i class="fa fa-users"></i>
            <span>Users</span>
        </a>
        <div id="collapseUser" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Users Components:</h6>
                <a class="collapse-item" href="{{ route('admin.user.form') }}">Add New</a>
                <a class="collapse-item" href="{{ route('admin.user.active') }}">Active</a>
                <a class="collapse-item" href="{{ route('admin.user.inActive') }}">In Active</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->