routes/admin.php
<?php
use Illuminate\Support\Facades\Route;


//we 'll not use admin prefix in this file because already fix in ROute service provider

Route::namespace('Admin')->prefix('admin')->as('admin.')->group(function (){
    Route::namespace('Auth')->group(function (){
//        Route::get('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('showLoginForm');
//        Route::post('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('login');
        Route::get('/login', [\App\Http\Controllers\Admin\AuthController::class, 'loginForm'])->name('showLoginForm');
        Route::post('/login', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login');
        Route::post('/logout', [\App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');
    });

    Route::get('/', [\App\Http\Controllers\Admin\AdminController::class, 'index'])->name('home');
    Route::get('/edit/{admin}', [\App\Http\Controllers\Admin\AdminController::class, 'editProfile'])->name('editProfile');
    Route::post('/update-profile', [\App\Http\Controllers\Admin\AdminController::class, 'updateProfile'])->name('updateProfile');


    //    Product Route's
    Route::namespace('Order')->prefix('orders')->as('order.')->group(function (){

        Route::get('/pending',[\App\Http\Controllers\Admin\Order\OrderController::class,'pending'])->name('pending');
        Route::get('/acceptedNew',[\App\Http\Controllers\Admin\Order\OrderController::class,'acceptedNew'])->name('acceptedNew');
        Route::get('/complete',[\App\Http\Controllers\Admin\Order\OrderController::class,'complete'])->name('complete');
        Route::get('/rejected',[\App\Http\Controllers\Admin\Order\OrderController::class,'rejected'])->name('rejected');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Order\OrderController::class,'changeStatus'])->name('changeStatus');
        Route::post('/order-accepted-status',[\App\Http\Controllers\Admin\Order\OrderController::class,'acceptedStatus'])->name('acceptedStatus');

    });

    // restaurants routes
    Route::namespace('Restaurant')->prefix('restaurants')->as('restaurant.')->group(function (){
        Route::get('/', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'approved'])->name('approved');
        Route::get('/pending', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'pending'])->name('pending');
        Route::get('/rejected', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'rejected'])->name('rejected');
        Route::get('/form', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'form'])->name('form');
        Route::post('/store', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'store'])->name('store');
        Route::post('/update', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'update'])->name('update');
        Route::post('/delete', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'destroy'])->name('delete');
        Route::post('/change-status', [\App\Http\Controllers\Admin\Restaurant\RestaurantsController::class, 'changeStatus'])->name('changeStatus');

    });

    // Users routes
    Route::namespace('User')->prefix('users')->as('user.')->group(function (){
        Route::get('/form', [\App\Http\Controllers\Admin\User\UsersController::class, 'form'])->name('form');
        Route::get('/active', [\App\Http\Controllers\Admin\User\UsersController::class, 'active'])->name('active');
        Route::get('/inactive', [\App\Http\Controllers\Admin\User\UsersController::class, 'inActive'])->name('inActive');
        Route::post('/store', [\App\Http\Controllers\Admin\User\UsersController::class, 'store'])->name('store');
//        Route::post('/edit/{id}', [\App\Http\Controllers\Admin\User\UsersController::class, 'edit'])->name('edit');
        Route::post('/update', [\App\Http\Controllers\Admin\User\UsersController::class, 'update'])->name('update');
        Route::post('/delete', [\App\Http\Controllers\Admin\User\UsersController::class, 'destroy'])->name('delete');
        Route::post('/change-status', [\App\Http\Controllers\Admin\User\UsersController::class, 'changeStatus'])->name('changeStatus');
    });

    //    Category Route's
    Route::namespace('Categories')->prefix('category')->as('category.')->group(function (){
        Route::get('/',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'create'])->name('create');
        Route::post('/store',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'update'])->name('update');
        Route::post('/delete',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'destroy'])->name('delete');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Categories\CategoryController::class,'changeStatus'])->name('changeStatus');
    });


//    Product Route's
    Route::namespace('Products')->prefix('product')->as('product.')->group(function (){

        Route::get('/approved',[\App\Http\Controllers\Admin\Products\ProductController::class,'approved'])->name('approved');
        Route::get('/pending',[\App\Http\Controllers\Admin\Products\ProductController::class,'pending'])->name('pending');
        Route::get('/rejected',[\App\Http\Controllers\Admin\Products\ProductController::class,'rejected'])->name('rejected');
        Route::post('/update',[\App\Http\Controllers\Admin\Products\ProductController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Products\ProductController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Admin\Products\ProductController::class,'delete'])->name('delete');

    });

    //    Product Route's
    Route::namespace('Deals')->prefix('deal')->as('deal.')->group(function (){

        Route::get('/approved',[App\Http\Controllers\Admin\Deals\DealController::class,'approved'])->name('approved');
        Route::get('/pending',[App\Http\Controllers\Admin\Deals\DealController::class,'pending'])->name('pending');
        Route::get('/rejected',[App\Http\Controllers\Admin\Deals\DealController::class,'rejected'])->name('rejected');
        Route::post('/change-status',[\App\Http\Controllers\Admin\Deals\DealController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Admin\Deals\DealController::class,'destroy'])->name('delete');

    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
//use App\Http\Controllers\Restaurant\RestaurantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::namespace('Restaurant')->prefix('restaurant')->as('restaurants.')->group(function (){
    Route::namespace('Auth')->group(function (){
//        Route::get('/login', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'showLoginForm'])->name('showLoginForm');
//        Route::post('/login', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'login'])->name('login');
//        Route::post('/logout', [\App\Http\Controllers\Restaurant\Auth\LoginController::class, 'logout'])->name('logout');
        Route::get('/register', [\App\Http\Controllers\Restaurant\Auth\RegisterController::class, 'showRegistrationForm'])->name('showRegistrationForm');
        Route::post('/register', [\App\Http\Controllers\Restaurant\Auth\RegisterController::class, 'register'])->name('register');

        Route::get('/login', [\App\Http\Controllers\Restaurant\AuthController::class, 'loginForm'])->name('showLoginForm');
        Route::post('/login', [\App\Http\Controllers\Restaurant\AuthController::class, 'login'])->name('login');
        Route::post('/logout', [\App\Http\Controllers\Restaurant\AuthController::class, 'logout'])->name('logout');
    });

    Route::middleware(['Restaurant'])->group(function(){

    Route::get('/', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'index'])->name('home');
    Route::get('/edit/{restaurant}', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'editProfile'])->name('editProfile');
    Route::post('/update-profile', [\App\Http\Controllers\Restaurant\RestaurantController::class, 'updateProfile'])->name('updateProfile');
    Route::get('/forget-password', [\App\Http\Controllers\Restaurant\ForgetPasswordController::class, 'forgetPassword'])->name('forgetPassword');
    Route::post('/new-password', [\App\Http\Controllers\Restaurant\ForgetPasswordController::class, 'newPassword'])->name('newPassword');





    // Category Route's
    Route::namespace('Categories')->prefix('category')->as('category.')->group(function (){
        Route::get('/',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'index'])->name('list');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'update'])->name('update');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'destroy'])->name('delete');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Categories\CategoryController::class,'changeStatus'])->name('changeStatus');
    });

    //    Deal Route's
    Route::namespace('Deal')->prefix('deal')->as('deal.')->group(function (){

        Route::get('/create',[App\Http\Controllers\Restaurant\Deal\DealController::class,'create'])->name('create');
        Route::get('/enable',[App\Http\Controllers\Restaurant\Deal\DealController::class,'enable'])->name('enable');
        Route::get('/disable',[App\Http\Controllers\Restaurant\Deal\DealController::class,'disable'])->name('disable');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Deal\DealController::class,'destroy'])->name('delete');

    });
    //    Product Route's
    Route::namespace('Order')->prefix('order')->as('order.')->group(function (){

        Route::get('/order-pending',[App\Http\Controllers\Restaurant\Order\OrderController::class,'pending'])->name('pending-order');
        Route::get('/order-accepted',[App\Http\Controllers\Restaurant\Order\OrderController::class,'accepted'])->name('accepted-order');
        Route::get('/order-complete',[App\Http\Controllers\Restaurant\Order\OrderController::class,'complete'])->name('complete-order');
        Route::get('/order-rejected',[App\Http\Controllers\Restaurant\Order\OrderController::class,'rejected'])->name('rejected-order');
        Route::post('/order-change-status',[App\Http\Controllers\Restaurant\Order\OrderController::class,'changeStatus'])->name('changeStatus-order');
        Route::post('/order-accepted-status',[App\Http\Controllers\Restaurant\Order\OrderController::class,'acceptedStatus'])->name('acceptedStatus-order');

    });
    //    Product Route's
    Route::namespace('Products')->prefix('product')->as('product.')->group(function (){

        Route::get('/create',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'create'])->name('create');
        Route::get('/approved',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'approved'])->name('approved');
        Route::get('/rejected',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'rejected'])->name('rejected');
        Route::get('/pending',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'pending'])->name('pending');
        Route::post('/store',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'store'])->name('store');
        Route::post('/update',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'update'])->name('update');
        Route::post('/change-status',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'changeStatus'])->name('changeStatus');
        Route::post('/delete',[\App\Http\Controllers\Restaurant\Products\ProductController::class,'destroy'])->name('delete');

    });

    });

});

Route::namespace("Web")->group(function (){
    /* Checkout routes */
    Route::get("checkout",[\App\Http\Controllers\Web\CheckoutController::class,"index"])->name('index');
    Route::get("restaurant/{slug}",[\App\Http\Controllers\Web\RestaurantController::class,"details"])->name('restaurant-detail');
    Route::get("orders",[\App\Http\Controllers\Web\OrderController::class,"index"])->name('orders');
});

//demo
Route::get('/', function () {
    return view('web.home');
});
Route::get('about',function (){
   return view('web.about');
});
Route::get('contact',function (){
    return view('web.contact');
});

Route::get('cart',function (){
    return view('web.cart');
});


Route::get('detail',function (){
    return view('web.detailpage');
});

Route::get('categoryproducts',function (){
    return view('web.categoryproduct');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $table = 'categories';

    public function products()
    {
        return $this->hasMany(Product::class,'category_id');
    }
}

app/Http/Controllers/API/Restaurant/CategoryController.php
<?php

namespace App\Http\Controllers\API\Restaurant;

use App\Http\Controllers\Controller;
use App\Services\API\Restaurant\CategoryServices;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function list(CategoryServices $categoryServices)
    {
        return $categoryServices->list();
    }
}

app/Http/Controllers/Admin/Categories/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Categories;

use App\Http\Controllers\Controller;
use App\Services\Categories\CategoryServices;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct()
    {
        return $this->middleware('auth:admin');
    }

    public function index(Request $request,CategoryServices $categoryServices)
    {
        return $categoryServices->index($request);
    }

    public function create(Request $request,CategoryServices $categoryServices)
    {
        return $categoryServices->create($request);
    }

    public function store(Request $request,CategoryServices $categoryServices)
    {
        return $categoryServices->store($request);
    }

    public function update(Request $request,CategoryServices $categoryServices)
    {
        return $categoryServices->update($request);
    }

    public function destroy(Request $request,CategoryServices $categoryServices)
    {
        return $categoryServices->destroy($request);
    }

    public function changeStatus(Request $request,CategoryServices $categoryServices)
    {
        return $categoryServices->changeStatus($request);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title','Create Category')
@section('content')
    <style>
        .form-control{
            height: auto;
        }
    </style>
    <div class="d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold">Add New Category</h6>
                </div>
                <div class="card-body">
                    <form class="add-category" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <div class="row mb-3">
                                <div class="col-6">
                                    <div class="form-group">
                                        <label class="input-label" for="exampleFormControlInput1">Name</label>
                                        <input type="text" name="name" class="form-control form-control-sm"
                                               placeholder="Enter Category Name">
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group">
                                        <label class="input-label" for="exampleFormControlInput1">Type</label>
                                        <input type="text" name="type" class="form-control form-control-sm"
                                               placeholder="Enter Category Type">
                                    </div>
                                </div>
                            </div>

                            <div class="row mb-3">

                                <div class="col-6">
                                    <label>Image</label>
                                    <div class="custom-file">
                                        <input type="file" name="image" id="customFileEg1" class="form-control"
                                               onchange="loadFile(event)">
                                        {{--                                    <label class="custom-file-label" for="customFileEg1"></label>--}}
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12">
                                    <div class="form-group">
                                        <center>
                                            <img class="mt-3 category-logo"
                                                 style="width: 30%;border: 1px solid; border-radius: 10px;"
                                                 id="output" src="{{ asset('assets/admin/img/noImageSelected.jpg') }}"
                                                 alt="image"/>
                                        </center>
                                    </div>
                                </div>
                            </div>


                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-primary" style="background: #ff982f;border: none;color: #fff;"  type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>

        /*IMAGE*/
        var loadFile = function (event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function () {
                URL.revokeObjectURL(output.src) // free memory
            }
        };

        $(document).ready(function () {
            /* START - AJAX code ADD restaurant */
            $('.add-category').on('submit', function (e) {
                e.preventDefault();
                var data = $('.add-category');
                data = new FormData(data[0]);
                //blockUi();
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: '{{route('admin.category.store')}}',
                    data: data,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $.unblockUI();
                        if (data.status === 1) {
                            successMsg(data.message);
                            $('#addCategoryModal').modal('hide');
                            // $('#addRestaurantModal').modal('toggle');
                            window.location.href = data.url;
                            //window.location.reload();
                        }
                        if (data.status === 0) {
                            errorMsg(data.message);
                        }
                    },
                    error: function (data) {
                        console.log('error');
                        $.unblockUI();
                    }
                });
            });
        });
        /* END - AJAX code ADD restaurant */
    </script>
@endsection